# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_students'),
        ('courses', '0002_auto_20180307_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='couse',
            name='courseorg',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organization.CourseOrg', verbose_name='\u6240\u5c5e\u673a\u6784'),
        ),
    ]
