# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-09 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_couse_courseorg'),
    ]

    operations = [
        migrations.AddField(
            model_name='couse',
            name='category',
            field=models.CharField(default='', max_length=50, verbose_name='\u8bfe\u7a0b\u7c7b\u522b'),
        ),
    ]
