# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-09 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_techer_image'),
        ('courses', '0005_couse_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='couse',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Techer'),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u89c6\u9891\u540d'),
        ),
    ]
