# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20180309_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='couse',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u8f6e\u64ad'),
        ),
    ]
