# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_couse_is_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='couse',
            name='is_classic',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u7ecf\u5178'),
        ),
    ]
