# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='catgory',
            field=models.CharField(choices=[('zf', '\u653f\u5e9c'), ('zuzhi', '\u7ec4\u7ec7'), ('geren', '\u4e2a\u4eba')], default='zf', max_length=20, verbose_name='\u7c7b\u578b'),
        ),
    ]
