# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-07 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_catgory'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='students',
            field=models.PositiveIntegerField(default=0, verbose_name='\u5b66\u751f\u6570'),
        ),
    ]
