# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_courseorg_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='course_num',
            field=models.PositiveIntegerField(default=0, verbose_name='\u8bfe\u7a0b\u6570'),
        ),
    ]
