# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-08 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_courseorg_course_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='techer',
            name='image',
            field=models.ImageField(default='', upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
