# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-12 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_techer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='\u5fd7\u9896\u6700\u7f8e', max_length=10, verbose_name='\u6807\u7b7e'),
        ),
    ]
